spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: hrms-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  sql:
    init:
      mode: never

server:
  port: 8080
  error:
    include-message: never
    include-binding-errors: never

app:
  frontend-url: ${FRONTEND_URL=https://meticulous-courage-production-58ee.up.railway.app}

  jwt:
    secret: ${JWT_SECRET:change_me_to_a_long_random_secret_change_me_to_a_long_random_secret}
    access-expiration-ms: ${JWT_ACCESS_EXPIRATION:900000}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION:604800000}

  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME:}
    api-key: ${CLOUDINARY_API_KEY:}
    api-secret: ${CLOUDINARY_API_SECRET:}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.boot: INFO
    org.springframework.jdbc: INFO
    org.hibernate: INFO